### ISSUE TITLE
[recommendation] don't use shebang #!/usr/bin/env python

### ISSUE THREAD

**Issue by tobwen** [muayyad-alsadi/podman-compose#1]
Please don't use shebang `#!/usr/bin/env python`. The reason is that python can refer either to _python2_ or _python3_ on different systems. On my current _Debian 9_, it seems to prefer _python3_...

So better use `#!/usr/bin/env python2`, which defaults to _Python 2.7.latest_

**Comment by muayyad-alsadi** [comment]
I'll make sure it works for both versions of python.

**Comment by tobwen** [comment]
Thx.

Could you please also add a list of dependencies needed? I think, I've covered all of them for _python2_, but it doesn't work with _python3_ on Debian here.

**Comment by muayyad-alsadi** [comment]
it just need yaml
