### ISSUE TITLE
[feature] view commands in debug/dry-run mode

### ISSUE THREAD

**Issue by tobwen** [muayyad-alsadi/podman-compose#2]
You you add a `--debug` switch to list all the commands instead of directly running _podman_? This would it make possible to debug everything or re-write it to shell-scripts to remove or add functionality.

**Comment by muayyad-alsadi** [comment]
sure, I'll do this.
mean while, it currently prints the commands you can copy them.

**Comment by tobwen** [comment]
Oops, seemsl ike my mobile message didn't get through. My problem is, _podman_ isn't in the search path (it's a local installation). So _pOpen_ fails and I can't get the complete command list.

I think, it might be better to call it `--dry-run` instead of `--debug` when _verbose output_ is activated by default?

**Comment by muayyad-alsadi** [comment]
valid request, I'll do it soon.

**Comment by tobwen** [comment]
yipee. Thx

**Comment by tobwen** [comment]
Please check https://github.com/muayyad-alsadi/podman-compose/pull/4

**Comment by tobwen** [comment]
#2 can be closed as implemented in https://github.com/muayyad-alsadi/podman-compose/pull/4
