### ISSUE TITLE
RuntimeError: Set changed size during iteration

### ISSUE THREAD

**Issue by TheEagle13** [muayyad-alsadi/podman-compose#20]
Hello, I seem to be having an issue, and I'm not sure what to try next. ( understand this is a WIP, but I would really like a way to move to podman from docker for my next big server install)
I have tried running as user, sudo, and root. I get the same error every time.

The command I'm using is: 
`./podman-compose.py -t 1podfw -f docker-compose.yml up`
both podman-compose and the docker compose file are in the same location currently (user home directory)
The compose file is for installing the mist.io platform. (https://github.com/mistio/mist-ce/releases/tag/v4.1.0)

The following is the error I get:
```Traceback (most recent call last):
  File "./podman-compose.py", line 747, in <module>
    main()
  File "./podman-compose.py", line 742, in main
    podman_path=args.podman_path
  File "./podman-compose.py", line 672, in run_compose
    flat_deps(container_names_by_service, container_by_name)
  File "./podman-compose.py", line 506, in flat_deps
    rec_deps(services, container_by_name, cnt, cnt.get('_service'))
  File "./podman-compose.py", line 484, in rec_deps
    for dep in deps:
RuntimeError: Set changed size during iteration
```

Any ideas on how to proceed?

**Comment by muayyad-alsadi** [comment]
I'll look into it ASAP

**Comment by TheEagle13** [comment]
Holy Cow that was a fast response! I appreciate your help!

**Comment by muayyad-alsadi** [comment]
it seems that `.copy()` in `for dep in deps.copy():` by @abraverm solved the issue

it's merged now, would you please confirm

**Comment by TheEagle13** [comment]
It does appear to have worked. I have other issues going on now that I need to troubleshoot, but your script appears to have done what it's supposed to. Thanks for your hard work!
