### ISSUE TITLE
Support ".yaml" file extension

### ISSUE THREAD

**Issue by chpio** [muayyad-alsadi/podman-compose#3]
> Is there an official extension for YAML files?
> Please use ".yaml" when possible.
>
> -- https://yaml.org/faq.html

**Comment by muayyad-alsadi** [comment]
you can pass `-f docker-compose.yaml`
if you want it to be the default, we are drop in replacement for `docker-compose` same defaults

```
$ docker-compose -h
Define and run multi-container applications with Docker.

Usage:
  docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
  docker-compose -h|--help

Options:
  -f, --file FILE             Specify an alternate compose file
                              (default: docker-compose.yml)
```

**Comment by chpio** [comment]
> we are drop in replacement for docker-compose

docker-compose *is* reading both extensions

**Comment by muayyad-alsadi** [comment]
this is a valid requirement, I'll make it look for `docker-compose.yml` and `docker-compose.yaml`

**Comment by chpio** [comment]
yeah, sorry for not mentioning that in my first comment
