### ISSUE TITLE
[feature request] support of `.env files`

### ISSUE THREAD

**Issue by tobwen** [muayyad-alsadi/podman-compose#5]
Is there a way to load the `.env files` (environment) used in newer dockerfiles?

https://github.com/mzazon/php-apache-mysql-containerized

**Comment by tobwen** [comment]
Hack on Debian 9

`( export $(cat .env | xargs) && envsubst < docker-compose.yml ) > docker-compose-env.yml`

**Comment by muayyad-alsadi** [comment]
the pointed file does not yet work because image is mandatory, build is not yet supported. see #6

**Comment by muayyad-alsadi** [comment]
@tobwen we support both build and .env, would you please test

**Comment by pruje** [comment]
I confirm that `.env` files are not loaded on podman-compose 0.1.7
(values are not replaced)

**Comment by heylix** [comment]
For me, `.env` files are only loaded when I specify them via `env_file` directive in `podman-compose.yml`, but not automagically.

**Comment by pickfire** [comment]
I was looking at https://docs.docker.com/compose/environment-variables/ and wondering why it `.env` wasn't loaded but with `env_file` it works, looks like it it is due to podman-compose after I went searching in github issues and found this.
