### ISSUE TITLE
Resolve relative volume paths to absolute paths

### ISSUE THREAD

**Issue by chpio** [muayyad-alsadi/podman-compose#7]
https://github.com/containers/libpod/issues/2301#issuecomment-476214940
or just wait for the fix

hmm, there's already a TODO comment for that `# TODO: make it absolute using os.path.realpath(i)`

**Comment by muayyad-alsadi** [comment]
> hmm, there's already a TODO comment for that # TODO: make it absolute using os.path.realpath(i)

yes, but that might require parsing the path for `:ro` or `:rw` ..etc.

**Comment by chpio** [comment]
wouldn't a simple split do the job? 
```
volume
  .split(":")
  .map(|v| absolutePath(v[0]).chain(v[1..]).join(":"))
```

**Comment by muayyad-alsadi** [comment]
I need to double check that format, currently I'm just passing it blindly 

https://docs.docker.com/compose/compose-file/#short-syntax-3

**Comment by muayyad-alsadi** [comment]
@chpio  please test
