### ISSUE TITLE
good news / bad news

### ISSUE THREAD

**Issue by tobwen** [muayyad-alsadi/podman-compose#8]
# good news
1. _Podman_ can run kubernetic files now rootless: https://github.com/containers/libpod/pull/2857
2. you can use https://github.com/kubernetes/kompose to convert `docker-compose` files up to v3.2
3. more details: https://developers.redhat.com/blog/2019/01/29/podman-kubernetes-yaml/ and the conversion matrix: https://github.com/kubernetes/kompose/blob/master/docs/conversion.md

# bad news
Maybe _podman-compose_ isn't needed anymore now :(

**Comment by muayyad-alsadi** [comment]
IMHO, it's still needed because

* this tool can do different types of mapping and transformations (like add-host to make links work unmodified)
* it has no dependency other than podman (k8s setup is complex).

**Comment by hnioche** [comment]
I've tried kompose, but wasn't able to have the resulting kubernetes files to run local dockerfiles. It behaves like podman-compose right now where it tries to pull containers from a repository. I'm not sure it will be implemented (or maybe it is and I missed something).

I also think that k8s is quite more complex than docker-compose, a bit too much for certain usecases.

**Comment by chpio** [comment]
also kubernetes isn't able to mount local host volumes?!

**Comment by tobwen** [comment]
Okay, I'm rejecting the good news :D
